# Generated by Django 2.2.9 on 2020-02-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, verbose_name='Ответ')),
                ('check', models.BooleanField(verbose_name='Проверка')),
            ],
        ),
    ]
